// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4VfwXpwDK_U_nWjuPAwXKR1ZPZNLn_vk',
    appId: '1:14155057690:web:0f6d6f474a03eb442a5fa3',
    messagingSenderId: '14155057690',
    projectId: 'cloudfirestore-filtering',
    authDomain: 'cloudfirestore-filtering.firebaseapp.com',
    storageBucket: 'cloudfirestore-filtering.appspot.com',
    measurementId: 'G-R74PYGQG8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyWDWi_CUDZfPH5INQHnebZyDm-yR5jB8',
    appId: '1:14155057690:android:a4ab6cf7103ad31f2a5fa3',
    messagingSenderId: '14155057690',
    projectId: 'cloudfirestore-filtering',
    storageBucket: 'cloudfirestore-filtering.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtICnjHMBvdPHrTgv2zlCPqfNQB7aR-o0',
    appId: '1:14155057690:ios:6ac782282e3af5192a5fa3',
    messagingSenderId: '14155057690',
    projectId: 'cloudfirestore-filtering',
    storageBucket: 'cloudfirestore-filtering.appspot.com',
    iosBundleId: 'com.example.filteringCloudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtICnjHMBvdPHrTgv2zlCPqfNQB7aR-o0',
    appId: '1:14155057690:ios:baf8a2806e103c862a5fa3',
    messagingSenderId: '14155057690',
    projectId: 'cloudfirestore-filtering',
    storageBucket: 'cloudfirestore-filtering.appspot.com',
    iosBundleId: 'com.example.filteringCloudFirestore.RunnerTests',
  );
}
